//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.07 at 11:30:48 AM GMT 
//


package org.jboss.shrinkwrap.descriptor.impl.spec.ee.ejbjar.javaee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 
 *         The concurrent-lock-typeType specifies how the container must
 *         manage concurrent access to a method of a Singleton bean 
 *         with container-managed concurrency.
 *         
 *         The container managed concurrency lock type must be one 
 *         of the following :
 *         
 *         Read
 *         Write
 *         
 *       
 * 
 * <p>Java class for concurrent-lock-typeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="concurrent-lock-typeType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://java.sun.com/xml/ns/javaee>string">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "concurrent-lock-typeType")
public class ConcurrentLockTypeType
    extends String
{


}
